--- #YAML:1.0
name:               File-EmptyDirs
version:            1.06
abstract:           find all empty directories in a path and remove recursively
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1
    Cwd:                  3
    Exporter:             5
    File::Find::Rule:     0.30
    File::Find::Rule::DirectoryEmpty:  1.11
    File::Path:           1.08
    LEOCHARRE::CLI2:      1.07
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
